site_name: Winsimple API

theme:
  favicon: images/favicon.png
  logo: images/Logomark (Black).svg
  name: material
  palette:
    # Light mode scheme
    - scheme: default
      primary: yellow
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode scheme
    - scheme: slate
      primary: yellow
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
